import type {
  BankAccount,
  BankTransaction,
  Invoice,
  Purchase,
} from "@/types/gst";

function d(offset: number): string {
  const dt = new Date();
  dt.setDate(dt.getDate() - offset);
  return dt.toISOString().split("T")[0];
}

function id(): string {
  return `seed-${Math.random().toString(36).slice(2, 10)}`;
}

export const SEED_INVOICES: Invoice[] = [
  {
    id: id(),
    type: "sales",
    invoiceNumber: "INV0001",
    date: d(5),
    dueDate: d(-25),
    partyId: "seed-party-1",
    partyName: "Tata Consultancy Services Ltd",
    partyGstin: "27AAACT2727Q1ZW",
    placeOfSupply: "27",
    placeOfSupplyName: "Maharashtra",
    lineItems: [
      {
        id: id(),
        itemId: "",
        description: "IT Consulting Services - Annual Package",
        hsnSacCode: "9983",
        qty: 1,
        unit: "Months",
        unitPrice: 150000,
        discountPercent: 5,
        gstRate: 18,
        cgst: 12825,
        sgst: 12825,
        igst: 0,
        cessPercent: 0,
        cess: 0,
        lineTotal: 167850,
      },
    ],
    subtotal: 150000,
    totalDiscount: 7500,
    totalCgst: 12825,
    totalSgst: 12825,
    totalIgst: 0,
    totalCess: 0,
    grandTotal: 167850,
    irnNumber: "d4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3",
    eWayBillNumber: "",
    notes: "Thank you for your continued business.",
    termsConditions: "Payment due within 30 days.",
    status: "confirmed",
    createdAt: new Date(d(5)).toISOString(),
    updatedAt: new Date(d(5)).toISOString(),
  },
  {
    id: id(),
    type: "sales",
    invoiceNumber: "INV0002",
    date: d(12),
    dueDate: d(-18),
    partyId: "seed-party-2",
    partyName: "Reliance Industries Ltd",
    partyGstin: "24AAACP4029D1ZN",
    placeOfSupply: "24",
    placeOfSupplyName: "Gujarat",
    lineItems: [
      {
        id: id(),
        itemId: "",
        description: "Software License - Enterprise Edition",
        hsnSacCode: "8523",
        qty: 10,
        unit: "Nos",
        unitPrice: 25000,
        discountPercent: 0,
        gstRate: 18,
        cgst: 0,
        sgst: 0,
        igst: 45000,
        cessPercent: 0,
        cess: 0,
        lineTotal: 295000,
      },
    ],
    subtotal: 250000,
    totalDiscount: 0,
    totalCgst: 0,
    totalSgst: 0,
    totalIgst: 45000,
    totalCess: 0,
    grandTotal: 295000,
    irnNumber: "",
    eWayBillNumber: "EWB-241234567890",
    notes: "",
    termsConditions: "Payment due within 15 days.",
    status: "confirmed",
    createdAt: new Date(d(12)).toISOString(),
    updatedAt: new Date(d(12)).toISOString(),
  },
  {
    id: id(),
    type: "service",
    invoiceNumber: "SRV0001",
    date: d(3),
    dueDate: d(-27),
    partyId: "seed-party-3",
    partyName: "Infosys Limited",
    partyGstin: "29AABCI0948N1ZA",
    placeOfSupply: "27",
    placeOfSupplyName: "Maharashtra",
    lineItems: [
      {
        id: id(),
        itemId: "",
        description: "Cloud Infrastructure Management",
        hsnSacCode: "9983",
        qty: 3,
        unit: "Months",
        unitPrice: 45000,
        discountPercent: 10,
        gstRate: 18,
        cgst: 7290,
        sgst: 7290,
        igst: 0,
        cessPercent: 0,
        cess: 0,
        lineTotal: 136080,
      },
      {
        id: id(),
        itemId: "",
        description: "24x7 Support Services",
        hsnSacCode: "9983",
        qty: 3,
        unit: "Months",
        unitPrice: 15000,
        discountPercent: 0,
        gstRate: 18,
        cgst: 2700,
        sgst: 2700,
        igst: 0,
        cessPercent: 0,
        cess: 0,
        lineTotal: 50400,
      },
    ],
    subtotal: 180000,
    totalDiscount: 13500,
    totalCgst: 9990,
    totalSgst: 9990,
    totalIgst: 0,
    totalCess: 0,
    grandTotal: 186480,
    irnNumber: "",
    eWayBillNumber: "",
    notes: "Services rendered as per SOW dated 01/01/2026.",
    termsConditions: "Payment due within 30 days.",
    status: "confirmed",
    createdAt: new Date(d(3)).toISOString(),
    updatedAt: new Date(d(3)).toISOString(),
  },
  {
    id: id(),
    type: "sales",
    invoiceNumber: "INV0003",
    date: d(1),
    dueDate: d(-29),
    partyId: "seed-party-4",
    partyName: "Wipro Technologies",
    partyGstin: "29AAACW0214A1Z1",
    placeOfSupply: "29",
    placeOfSupplyName: "Karnataka",
    lineItems: [
      {
        id: id(),
        itemId: "",
        description: "Hardware Components - Server Rack",
        hsnSacCode: "8471",
        qty: 2,
        unit: "Nos",
        unitPrice: 85000,
        discountPercent: 5,
        gstRate: 18,
        cgst: 0,
        sgst: 0,
        igst: 28900,
        cessPercent: 0,
        cess: 0,
        lineTotal: 189900,
      },
    ],
    subtotal: 170000,
    totalDiscount: 8500,
    totalCgst: 0,
    totalSgst: 0,
    totalIgst: 28900,
    totalCess: 0,
    grandTotal: 190400,
    irnNumber: "",
    eWayBillNumber: "",
    notes: "",
    termsConditions: "Payment due within 30 days. Goods not returnable.",
    status: "draft",
    createdAt: new Date(d(1)).toISOString(),
    updatedAt: new Date(d(1)).toISOString(),
  },
  {
    id: id(),
    type: "quotation",
    invoiceNumber: "QUO0001",
    date: d(2),
    dueDate: d(28),
    partyId: "seed-party-5",
    partyName: "HCL Technologies",
    partyGstin: "06AABCH7111Q1Z5",
    placeOfSupply: "27",
    placeOfSupplyName: "Maharashtra",
    lineItems: [
      {
        id: id(),
        itemId: "",
        description: "Digital Transformation Consulting",
        hsnSacCode: "9983",
        qty: 6,
        unit: "Months",
        unitPrice: 75000,
        discountPercent: 0,
        gstRate: 18,
        cgst: 40500,
        sgst: 40500,
        igst: 0,
        cessPercent: 0,
        cess: 0,
        lineTotal: 531000,
      },
    ],
    subtotal: 450000,
    totalDiscount: 0,
    totalCgst: 40500,
    totalSgst: 40500,
    totalIgst: 0,
    totalCess: 0,
    grandTotal: 531000,
    irnNumber: "",
    eWayBillNumber: "",
    notes: "Quotation valid for 30 days.",
    termsConditions: "Subject to formal PO.",
    status: "draft",
    createdAt: new Date(d(2)).toISOString(),
    updatedAt: new Date(d(2)).toISOString(),
  },
];

export const SEED_PURCHASES: Purchase[] = [
  {
    id: id(),
    billNumber: "BILL0001",
    billDate: d(8),
    dueDate: d(-22),
    vendorId: "seed-vendor-1",
    vendorName: "Amazon Web Services India",
    vendorGstin: "29AANCA7727Q1ZY",
    lineItems: [
      {
        id: id(),
        itemId: "",
        description: "EC2 Compute - Monthly Bill",
        hsnSacCode: "9983",
        qty: 1,
        unit: "Months",
        unitPrice: 85000,
        discountPercent: 0,
        gstRate: 18,
        cgst: 7650,
        sgst: 7650,
        igst: 0,
        cessPercent: 0,
        cess: 0,
        lineTotal: 100300,
      },
    ],
    subtotal: 85000,
    totalDiscount: 0,
    totalCgst: 7650,
    totalSgst: 7650,
    totalIgst: 0,
    totalCess: 0,
    grandTotal: 100300,
    isRcm: false,
    itcEligible: true,
    status: "confirmed",
    notes: "",
    createdAt: new Date(d(8)).toISOString(),
    updatedAt: new Date(d(8)).toISOString(),
  },
  {
    id: id(),
    billNumber: "BILL0002",
    billDate: d(15),
    dueDate: d(-15),
    vendorId: "seed-vendor-2",
    vendorName: "Microsoft India Pvt Ltd",
    vendorGstin: "07AAACM1756M1ZG",
    lineItems: [
      {
        id: id(),
        itemId: "",
        description: "Office 365 Enterprise - Annual",
        hsnSacCode: "9983",
        qty: 50,
        unit: "Nos",
        unitPrice: 1200,
        discountPercent: 10,
        gstRate: 18,
        cgst: 4860,
        sgst: 4860,
        igst: 0,
        cessPercent: 0,
        cess: 0,
        lineTotal: 63720,
      },
    ],
    subtotal: 60000,
    totalDiscount: 6000,
    totalCgst: 4860,
    totalSgst: 4860,
    totalIgst: 0,
    totalCess: 0,
    grandTotal: 63720,
    isRcm: false,
    itcEligible: true,
    status: "confirmed",
    notes: "",
    createdAt: new Date(d(15)).toISOString(),
    updatedAt: new Date(d(15)).toISOString(),
  },
  {
    id: id(),
    billNumber: "BILL0003",
    billDate: d(20),
    dueDate: d(-10),
    vendorId: "seed-vendor-3",
    vendorName: "Tata Power Company Ltd",
    vendorGstin: "27AAACT5600E1ZV",
    lineItems: [
      {
        id: id(),
        itemId: "",
        description: "Electricity - Office Premises",
        hsnSacCode: "2716",
        qty: 1,
        unit: "Months",
        unitPrice: 35000,
        discountPercent: 0,
        gstRate: 5,
        cgst: 875,
        sgst: 875,
        igst: 0,
        cessPercent: 0,
        cess: 0,
        lineTotal: 36750,
      },
    ],
    subtotal: 35000,
    totalDiscount: 0,
    totalCgst: 875,
    totalSgst: 875,
    totalIgst: 0,
    totalCess: 0,
    grandTotal: 36750,
    isRcm: false,
    itcEligible: false,
    status: "confirmed",
    notes: "",
    createdAt: new Date(d(20)).toISOString(),
    updatedAt: new Date(d(20)).toISOString(),
  },
];

export const SEED_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: "seed-bank-1",
    bankName: "State Bank of India",
    accountNumber: "10234567890",
    ifsc: "SBIN0001234",
    openingBalance: 2500000,
    accountType: "current",
    isActive: true,
    createdAt: new Date(d(90)).toISOString(),
  },
  {
    id: "seed-bank-2",
    bankName: "HDFC Bank",
    accountNumber: "50100234567890",
    ifsc: "HDFC0000123",
    openingBalance: 750000,
    accountType: "savings",
    isActive: true,
    createdAt: new Date(d(90)).toISOString(),
  },
];

export const SEED_TRANSACTIONS: BankTransaction[] = [
  {
    id: id(),
    accountId: "seed-bank-1",
    date: d(5),
    description: "TCS Invoice Payment Received",
    debit: 0,
    credit: 167850,
    balance: 2667850,
    reference: "UTR2024030123456",
    createdAt: new Date(d(5)).toISOString(),
  },
  {
    id: id(),
    accountId: "seed-bank-1",
    date: d(8),
    description: "AWS Cloud Services Payment",
    debit: 100300,
    credit: 0,
    balance: 2567550,
    reference: "NEFT20240302",
    createdAt: new Date(d(8)).toISOString(),
  },
  {
    id: id(),
    accountId: "seed-bank-1",
    date: d(12),
    description: "Reliance License Payment Received",
    debit: 0,
    credit: 295000,
    balance: 2862550,
    reference: "RTGS20240301",
    createdAt: new Date(d(12)).toISOString(),
  },
];

export function seedInitialData() {
  // Only seed if the user has never saved any data (truly first-time load)
  // Guard: if a business profile already exists, the user has real data — never overwrite
  if (localStorage.getItem("gst_business_profile")) return;
  if (localStorage.getItem("gst_seeded")) return;

  localStorage.setItem("gst_invoices", JSON.stringify(SEED_INVOICES));
  localStorage.setItem("gst_purchases", JSON.stringify(SEED_PURCHASES));
  localStorage.setItem("gst_bank_accounts", JSON.stringify(SEED_BANK_ACCOUNTS));
  localStorage.setItem(
    "gst_bank_transactions",
    JSON.stringify(SEED_TRANSACTIONS),
  );
  localStorage.setItem(
    "gst_invoice_counters",
    JSON.stringify({
      sales: 3,
      service: 1,
      quotation: 1,
      purchase: 3,
      journal: 0,
    }),
  );
  localStorage.setItem("gst_seeded", "true");
}
