/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessProfile {
  'stateCode' : bigint,
  'businessName' : string,
  'gstin' : string,
  'address' : string,
  'registrationType' : RegistrationType,
  'contactDetails' : string,
}
export interface Item {
  'id' : NatId,
  'purchasePrice' : bigint,
  'name' : string,
  'unit' : bigint,
  'sellingPrice' : bigint,
  'description' : string,
  'cessPercent' : bigint,
  'isActive' : boolean,
  'itemType' : ItemType,
  'gstRate' : bigint,
  'hsnSacCode' : string,
  'openingStock' : bigint,
}
export type ItemType = { 'service' : null } |
  { 'goods' : null };
export type NatId = bigint;
export interface Party {
  'id' : NatId,
  'pan' : string,
  'stateCode' : bigint,
  'billingAddress' : string,
  'name' : string,
  'isActive' : boolean,
  'email' : string,
  'gstin' : string,
  'shippingAddress' : string,
  'partyType' : PartyType,
  'phone' : string,
}
export type PartyType = { 'customer' : null } |
  { 'both' : null } |
  { 'vendor' : null };
export type RegistrationType = { 'unregistered' : null } |
  { 'regular' : null } |
  { 'composition' : null };
export interface TaxRate {
  'id' : NatId,
  'gstRatePercent' : bigint,
  'isExempt' : boolean,
  'isRcmApplicable' : boolean,
  'name' : string,
  'description' : string,
  'cessPercent' : bigint,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export interface _SERVICE {
  'addItem' : ActorMethod<[Item], NatId>,
  'addParty' : ActorMethod<[Party], NatId>,
  'addTaxRate' : ActorMethod<[TaxRate], NatId>,
  'deleteBusinessRecord' : ActorMethod<[string], undefined>,
  'deleteCloudData' : ActorMethod<[string], undefined>,
  'deleteEntityRecord' : ActorMethod<[string, string, string], undefined>,
  'deleteItem' : ActorMethod<[NatId], undefined>,
  'deleteParty' : ActorMethod<[NatId], undefined>,
  'deleteTaxRate' : ActorMethod<[NatId], undefined>,
  'getAllBusinessRecords' : ActorMethod<[], Array<string>>,
  'getAllCloudData' : ActorMethod<[], Array<[string, string]>>,
  'getAllEntityRecords' : ActorMethod<[string, string], Array<string>>,
  'getAllItems' : ActorMethod<[], Array<Item>>,
  'getAllParties' : ActorMethod<[], Array<Party>>,
  'getAllTaxRates' : ActorMethod<[], Array<TaxRate>>,
  'getBizConfig' : ActorMethod<[string, string], [] | [string]>,
  'getBusinessProfile' : ActorMethod<[], [] | [BusinessProfile]>,
  'getBusinessRecord' : ActorMethod<[string], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCloudData' : ActorMethod<[string], [] | [string]>,
  'getEntityRecord' : ActorMethod<[string, string, string], [] | [string]>,
  'getItem' : ActorMethod<[NatId], [] | [Item]>,
  'getLastSyncTime' : ActorMethod<[], [] | [bigint]>,
  'getNextInvoiceNumber' : ActorMethod<[string, string, string], string>,
  'getParty' : ActorMethod<[NatId], [] | [Party]>,
  'getTaxRate' : ActorMethod<[NatId], [] | [TaxRate]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'saveBizConfig' : ActorMethod<[string, string, string], undefined>,
  'saveBusinessRecord' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCloudData' : ActorMethod<[string, string], undefined>,
  'saveEntityRecord' : ActorMethod<[string, string, string, string], undefined>,
  'setBusinessProfile' : ActorMethod<[BusinessProfile], undefined>,
  'updateItem' : ActorMethod<[NatId, Item], undefined>,
  'updateParty' : ActorMethod<[NatId, Party], undefined>,
  'updateTaxRate' : ActorMethod<[NatId, TaxRate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];