/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NatId = IDL.Nat;
export const ItemType = IDL.Variant({
  'service' : IDL.Null,
  'goods' : IDL.Null,
});
export const Item = IDL.Record({
  'id' : NatId,
  'purchasePrice' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Nat,
  'sellingPrice' : IDL.Nat,
  'description' : IDL.Text,
  'cessPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
  'itemType' : ItemType,
  'gstRate' : IDL.Nat,
  'hsnSacCode' : IDL.Text,
  'openingStock' : IDL.Nat,
});
export const PartyType = IDL.Variant({
  'customer' : IDL.Null,
  'both' : IDL.Null,
  'vendor' : IDL.Null,
});
export const Party = IDL.Record({
  'id' : NatId,
  'pan' : IDL.Text,
  'stateCode' : IDL.Int,
  'billingAddress' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'gstin' : IDL.Text,
  'shippingAddress' : IDL.Text,
  'partyType' : PartyType,
  'phone' : IDL.Text,
});
export const TaxRate = IDL.Record({
  'id' : NatId,
  'gstRatePercent' : IDL.Nat,
  'isExempt' : IDL.Bool,
  'isRcmApplicable' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'cessPercent' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RegistrationType = IDL.Variant({
  'unregistered' : IDL.Null,
  'regular' : IDL.Null,
  'composition' : IDL.Null,
});
export const BusinessProfile = IDL.Record({
  'stateCode' : IDL.Nat,
  'businessName' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'registrationType' : RegistrationType,
  'contactDetails' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addItem' : IDL.Func([Item], [NatId], []),
  'addParty' : IDL.Func([Party], [NatId], []),
  'addTaxRate' : IDL.Func([TaxRate], [NatId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteItem' : IDL.Func([NatId], [], []),
  'deleteParty' : IDL.Func([NatId], [], []),
  'deleteTaxRate' : IDL.Func([NatId], [], []),
  'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getAllParties' : IDL.Func([], [IDL.Vec(Party)], ['query']),
  'getAllTaxRates' : IDL.Func([], [IDL.Vec(TaxRate)], ['query']),
  'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItem' : IDL.Func([NatId], [IDL.Opt(Item)], ['query']),
  'getParty' : IDL.Func([NatId], [IDL.Opt(Party)], ['query']),
  'getTaxRate' : IDL.Func([NatId], [IDL.Opt(TaxRate)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBusinessProfile' : IDL.Func([BusinessProfile], [], []),
  'updateItem' : IDL.Func([NatId, Item], [], []),
  'updateParty' : IDL.Func([NatId, Party], [], []),
  'updateTaxRate' : IDL.Func([NatId, TaxRate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NatId = IDL.Nat;
  const ItemType = IDL.Variant({ 'service' : IDL.Null, 'goods' : IDL.Null });
  const Item = IDL.Record({
    'id' : NatId,
    'purchasePrice' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Nat,
    'sellingPrice' : IDL.Nat,
    'description' : IDL.Text,
    'cessPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
    'itemType' : ItemType,
    'gstRate' : IDL.Nat,
    'hsnSacCode' : IDL.Text,
    'openingStock' : IDL.Nat,
  });
  const PartyType = IDL.Variant({
    'customer' : IDL.Null,
    'both' : IDL.Null,
    'vendor' : IDL.Null,
  });
  const Party = IDL.Record({
    'id' : NatId,
    'pan' : IDL.Text,
    'stateCode' : IDL.Int,
    'billingAddress' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'gstin' : IDL.Text,
    'shippingAddress' : IDL.Text,
    'partyType' : PartyType,
    'phone' : IDL.Text,
  });
  const TaxRate = IDL.Record({
    'id' : NatId,
    'gstRatePercent' : IDL.Nat,
    'isExempt' : IDL.Bool,
    'isRcmApplicable' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'cessPercent' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RegistrationType = IDL.Variant({
    'unregistered' : IDL.Null,
    'regular' : IDL.Null,
    'composition' : IDL.Null,
  });
  const BusinessProfile = IDL.Record({
    'stateCode' : IDL.Nat,
    'businessName' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'registrationType' : RegistrationType,
    'contactDetails' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addItem' : IDL.Func([Item], [NatId], []),
    'addParty' : IDL.Func([Party], [NatId], []),
    'addTaxRate' : IDL.Func([TaxRate], [NatId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteItem' : IDL.Func([NatId], [], []),
    'deleteParty' : IDL.Func([NatId], [], []),
    'deleteTaxRate' : IDL.Func([NatId], [], []),
    'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getAllParties' : IDL.Func([], [IDL.Vec(Party)], ['query']),
    'getAllTaxRates' : IDL.Func([], [IDL.Vec(TaxRate)], ['query']),
    'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItem' : IDL.Func([NatId], [IDL.Opt(Item)], ['query']),
    'getParty' : IDL.Func([NatId], [IDL.Opt(Party)], ['query']),
    'getTaxRate' : IDL.Func([NatId], [IDL.Opt(TaxRate)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBusinessProfile' : IDL.Func([BusinessProfile], [], []),
    'updateItem' : IDL.Func([NatId, Item], [], []),
    'updateParty' : IDL.Func([NatId, Party], [], []),
    'updateTaxRate' : IDL.Func([NatId, TaxRate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };