/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NatId = IDL.Nat;
export const ItemType = IDL.Variant({
  'service' : IDL.Null,
  'goods' : IDL.Null,
});
export const Item = IDL.Record({
  'id' : NatId,
  'purchasePrice' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Nat,
  'sellingPrice' : IDL.Nat,
  'description' : IDL.Text,
  'cessPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
  'itemType' : ItemType,
  'gstRate' : IDL.Nat,
  'hsnSacCode' : IDL.Text,
  'openingStock' : IDL.Nat,
});
export const PartyType = IDL.Variant({
  'customer' : IDL.Null,
  'both' : IDL.Null,
  'vendor' : IDL.Null,
});
export const Party = IDL.Record({
  'id' : NatId,
  'pan' : IDL.Text,
  'stateCode' : IDL.Int,
  'billingAddress' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'gstin' : IDL.Text,
  'shippingAddress' : IDL.Text,
  'partyType' : PartyType,
  'phone' : IDL.Text,
});
export const TaxRate = IDL.Record({
  'id' : NatId,
  'gstRatePercent' : IDL.Nat,
  'isExempt' : IDL.Bool,
  'isRcmApplicable' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'cessPercent' : IDL.Nat,
});
export const RegistrationType = IDL.Variant({
  'unregistered' : IDL.Null,
  'regular' : IDL.Null,
  'composition' : IDL.Null,
});
export const BusinessProfile = IDL.Record({
  'stateCode' : IDL.Nat,
  'businessName' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'registrationType' : RegistrationType,
  'contactDetails' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'addItem' : IDL.Func([Item], [NatId], []),
  'addParty' : IDL.Func([Party], [NatId], []),
  'addTaxRate' : IDL.Func([TaxRate], [NatId], []),
  'deleteBusinessRecord' : IDL.Func([IDL.Text], [], []),
  'deleteCloudData' : IDL.Func([IDL.Text], [], []),
  'deleteEntityRecord' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteItem' : IDL.Func([NatId], [], []),
  'deleteParty' : IDL.Func([NatId], [], []),
  'deleteTaxRate' : IDL.Func([NatId], [], []),
  'getAllBusinessRecords' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllCloudData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllEntityRecords' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getAllParties' : IDL.Func([], [IDL.Vec(Party)], ['query']),
  'getAllTaxRates' : IDL.Func([], [IDL.Vec(TaxRate)], ['query']),
  'getBizConfig' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
  'getBusinessRecord' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCloudData' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getEntityRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getItem' : IDL.Func([NatId], [IDL.Opt(Item)], ['query']),
  'getLastSyncTime' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getNextInvoiceNumber' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getParty' : IDL.Func([NatId], [IDL.Opt(Party)], ['query']),
  'getTaxRate' : IDL.Func([NatId], [IDL.Opt(TaxRate)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'saveBizConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveBusinessRecord' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCloudData' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveEntityRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'setBusinessProfile' : IDL.Func([BusinessProfile], [], []),
  'updateItem' : IDL.Func([NatId, Item], [], []),
  'updateParty' : IDL.Func([NatId, Party], [], []),
  'updateTaxRate' : IDL.Func([NatId, TaxRate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NatId = IDL.Nat;
  const ItemType = IDL.Variant({ 'service' : IDL.Null, 'goods' : IDL.Null });
  const Item = IDL.Record({
    'id' : NatId,
    'purchasePrice' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Nat,
    'sellingPrice' : IDL.Nat,
    'description' : IDL.Text,
    'cessPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
    'itemType' : ItemType,
    'gstRate' : IDL.Nat,
    'hsnSacCode' : IDL.Text,
    'openingStock' : IDL.Nat,
  });
  const PartyType = IDL.Variant({
    'customer' : IDL.Null,
    'both' : IDL.Null,
    'vendor' : IDL.Null,
  });
  const Party = IDL.Record({
    'id' : NatId,
    'pan' : IDL.Text,
    'stateCode' : IDL.Int,
    'billingAddress' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'gstin' : IDL.Text,
    'shippingAddress' : IDL.Text,
    'partyType' : PartyType,
    'phone' : IDL.Text,
  });
  const TaxRate = IDL.Record({
    'id' : NatId,
    'gstRatePercent' : IDL.Nat,
    'isExempt' : IDL.Bool,
    'isRcmApplicable' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'cessPercent' : IDL.Nat,
  });
  const RegistrationType = IDL.Variant({
    'unregistered' : IDL.Null,
    'regular' : IDL.Null,
    'composition' : IDL.Null,
  });
  const BusinessProfile = IDL.Record({
    'stateCode' : IDL.Nat,
    'businessName' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'registrationType' : RegistrationType,
    'contactDetails' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'addItem' : IDL.Func([Item], [NatId], []),
    'addParty' : IDL.Func([Party], [NatId], []),
    'addTaxRate' : IDL.Func([TaxRate], [NatId], []),
    'deleteBusinessRecord' : IDL.Func([IDL.Text], [], []),
    'deleteCloudData' : IDL.Func([IDL.Text], [], []),
    'deleteEntityRecord' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteItem' : IDL.Func([NatId], [], []),
    'deleteParty' : IDL.Func([NatId], [], []),
    'deleteTaxRate' : IDL.Func([NatId], [], []),
    'getAllBusinessRecords' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllCloudData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllEntityRecords' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getAllParties' : IDL.Func([], [IDL.Vec(Party)], ['query']),
    'getAllTaxRates' : IDL.Func([], [IDL.Vec(TaxRate)], ['query']),
    'getBizConfig' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
    'getBusinessRecord' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCloudData' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getEntityRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getItem' : IDL.Func([NatId], [IDL.Opt(Item)], ['query']),
    'getLastSyncTime' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getNextInvoiceNumber' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getParty' : IDL.Func([NatId], [IDL.Opt(Party)], ['query']),
    'getTaxRate' : IDL.Func([NatId], [IDL.Opt(TaxRate)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'saveBizConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveBusinessRecord' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCloudData' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveEntityRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'setBusinessProfile' : IDL.Func([BusinessProfile], [], []),
    'updateItem' : IDL.Func([NatId, Item], [], []),
    'updateParty' : IDL.Func([NatId, Party], [], []),
    'updateTaxRate' : IDL.Func([NatId, TaxRate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };