/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TaxRate {
    id: NatId;
    gstRatePercent: bigint;
    isExempt: boolean;
    isRcmApplicable: boolean;
    name: string;
    description: string;
    cessPercent: bigint;
}
export type NatId = bigint;
export interface Item {
    id: NatId;
    purchasePrice: bigint;
    name: string;
    unit: bigint;
    sellingPrice: bigint;
    description: string;
    cessPercent: bigint;
    isActive: boolean;
    itemType: ItemType;
    gstRate: bigint;
    hsnSacCode: string;
    openingStock: bigint;
}
export interface Party {
    id: NatId;
    pan: string;
    stateCode: bigint;
    billingAddress: string;
    name: string;
    isActive: boolean;
    email: string;
    gstin: string;
    shippingAddress: string;
    partyType: PartyType;
    phone: string;
}
export interface BusinessProfile {
    stateCode: bigint;
    businessName: string;
    gstin: string;
    address: string;
    registrationType: RegistrationType;
    contactDetails: string;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export enum ItemType {
    service = "service",
    goods = "goods"
}
export enum PartyType {
    customer = "customer",
    both = "both",
    vendor = "vendor"
}
export enum RegistrationType {
    unregistered = "unregistered",
    regular = "regular",
    composition = "composition"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addItem(item: Item): Promise<NatId>;
    addParty(party: Party): Promise<NatId>;
    addTaxRate(taxRate: TaxRate): Promise<NatId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteItem(id: NatId): Promise<void>;
    deleteParty(id: NatId): Promise<void>;
    deleteTaxRate(id: NatId): Promise<void>;
    getAllItems(): Promise<Array<Item>>;
    getAllParties(): Promise<Array<Party>>;
    getAllTaxRates(): Promise<Array<TaxRate>>;
    getBusinessProfile(): Promise<BusinessProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getItem(id: NatId): Promise<Item | null>;
    getParty(id: NatId): Promise<Party | null>;
    getTaxRate(id: NatId): Promise<TaxRate | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setBusinessProfile(profile: BusinessProfile): Promise<void>;
    updateItem(id: NatId, updatedItem: Item): Promise<void>;
    updateParty(id: NatId, updatedParty: Party): Promise<void>;
    updateTaxRate(id: NatId, updatedTaxRate: TaxRate): Promise<void>;
    // Cloud sync
    saveCloudData(key: string, value: string): Promise<void>;
    getCloudData(key: string): Promise<string | null>;
    getAllCloudData(): Promise<Array<[string, string]>>;
    getLastSyncTime(): Promise<bigint | null>;
    deleteCloudData(key: string): Promise<void>;
    // Multi-business management
    saveBusinessRecord(id: string, recordJson: string): Promise<void>;
    getBusinessRecord(id: string): Promise<string | null>;
    getAllBusinessRecords(): Promise<string[]>;
    deleteBusinessRecord(id: string): Promise<void>;
    // Generic per-business entity CRUD
    saveEntityRecord(bizId: string, entityType: string, id: string, recordJson: string): Promise<void>;
    getEntityRecord(bizId: string, entityType: string, id: string): Promise<string | null>;
    getAllEntityRecords(bizId: string, entityType: string): Promise<string[]>;
    deleteEntityRecord(bizId: string, entityType: string, id: string): Promise<void>;
    // Business config
    saveBizConfig(bizId: string, configKey: string, value: string): Promise<void>;
    getBizConfig(bizId: string, configKey: string): Promise<string | null>;
    // Invoice counter
    getNextInvoiceNumber(bizId: string, counterType: string, prefix: string): Promise<string>;
}
import type { BusinessProfile as _BusinessProfile, Item as _Item, ItemType as _ItemType, NatId as _NatId, Party as _Party, PartyType as _PartyType, RegistrationType as _RegistrationType, TaxRate as _TaxRate, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addItem(arg0: Item): Promise<NatId> {
        if (this.processError) {
            try {
                const result = await this.actor.addItem(to_candid_Item_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItem(to_candid_Item_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addParty(arg0: Party): Promise<NatId> {
        if (this.processError) {
            try {
                const result = await this.actor.addParty(to_candid_Party_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addParty(to_candid_Party_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTaxRate(arg0: TaxRate): Promise<NatId> {
        if (this.processError) {
            try {
                const result = await this.actor.addTaxRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTaxRate(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteItem(arg0: NatId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItem(arg0);
            return result;
        }
    }
    async deleteParty(arg0: NatId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteParty(arg0);
            return result;
        }
    }
    async deleteTaxRate(arg0: NatId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTaxRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTaxRate(arg0);
            return result;
        }
    }
    async getAllItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllItems();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllItems();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllParties(): Promise<Array<Party>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllParties();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllParties();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTaxRates(): Promise<Array<TaxRate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTaxRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTaxRates();
            return result;
        }
    }
    async getBusinessProfile(): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItem(arg0: NatId): Promise<Item | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItem(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItem(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getParty(arg0: NatId): Promise<Party | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getParty(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParty(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaxRate(arg0: NatId): Promise<TaxRate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaxRate(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaxRate(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setBusinessProfile(arg0: BusinessProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBusinessProfile(to_candid_BusinessProfile_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBusinessProfile(to_candid_BusinessProfile_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateItem(arg0: NatId, arg1: Item): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItem(arg0, to_candid_Item_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItem(arg0, to_candid_Item_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateParty(arg0: NatId, arg1: Party): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParty(arg0, to_candid_Party_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParty(arg0, to_candid_Party_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTaxRate(arg0: NatId, arg1: TaxRate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaxRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaxRate(arg0, arg1);
            return result;
        }
    }
    // ─── Cloud sync methods ──────────────────────────────────────────────────
    async saveCloudData(key: string, value: string): Promise<void> {
        const result = await (this.actor as any).saveCloudData(key, value);
        return result;
    }
    async getCloudData(key: string): Promise<string | null> {
        const result = await (this.actor as any).getCloudData(key);
        return result && result.length > 0 ? result[0] : null;
    }
    async getAllCloudData(): Promise<Array<[string, string]>> {
        const result = await (this.actor as any).getAllCloudData();
        return result;
    }
    async getLastSyncTime(): Promise<bigint | null> {
        const result = await (this.actor as any).getLastSyncTime();
        return result && result.length > 0 ? result[0] : null;
    }
    async deleteCloudData(key: string): Promise<void> {
        const result = await (this.actor as any).deleteCloudData(key);
        return result;
    }
    // ─── New backend methods for database storage ─────────────────────────────
    async saveBusinessRecord(id: string, recordJson: string): Promise<void> {
        const result = await (this.actor as any).saveBusinessRecord(id, recordJson);
        return result;
    }
    async getBusinessRecord(id: string): Promise<string | null> {
        const result = await (this.actor as any).getBusinessRecord(id);
        return result && result.length > 0 ? result[0] : null;
    }
    async getAllBusinessRecords(): Promise<string[]> {
        const result = await (this.actor as any).getAllBusinessRecords();
        return result;
    }
    async deleteBusinessRecord(id: string): Promise<void> {
        const result = await (this.actor as any).deleteBusinessRecord(id);
        return result;
    }
    async saveEntityRecord(bizId: string, entityType: string, id: string, recordJson: string): Promise<void> {
        const result = await (this.actor as any).saveEntityRecord(bizId, entityType, id, recordJson);
        return result;
    }
    async getEntityRecord(bizId: string, entityType: string, id: string): Promise<string | null> {
        const result = await (this.actor as any).getEntityRecord(bizId, entityType, id);
        return result && result.length > 0 ? result[0] : null;
    }
    async getAllEntityRecords(bizId: string, entityType: string): Promise<string[]> {
        const result = await (this.actor as any).getAllEntityRecords(bizId, entityType);
        return result;
    }
    async deleteEntityRecord(bizId: string, entityType: string, id: string): Promise<void> {
        const result = await (this.actor as any).deleteEntityRecord(bizId, entityType, id);
        return result;
    }
    async saveBizConfig(bizId: string, configKey: string, value: string): Promise<void> {
        const result = await (this.actor as any).saveBizConfig(bizId, configKey, value);
        return result;
    }
    async getBizConfig(bizId: string, configKey: string): Promise<string | null> {
        const result = await (this.actor as any).getBizConfig(bizId, configKey);
        return result && result.length > 0 ? result[0] : null;
    }
    async getNextInvoiceNumber(bizId: string, counterType: string, prefix: string): Promise<string> {
        const result = await (this.actor as any).getNextInvoiceNumber(bizId, counterType, prefix);
        return result;
    }
}
function from_candid_BusinessProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessProfile): BusinessProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ItemType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemType): ItemType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Item_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Item): Item {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PartyType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartyType): PartyType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Party_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Party): Party {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationType): RegistrationType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusinessProfile]): BusinessProfile | null {
    return value.length === 0 ? null : from_candid_BusinessProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Item]): Item | null {
    return value.length === 0 ? null : from_candid_Item_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Party]): Party | null {
    return value.length === 0 ? null : from_candid_Party_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaxRate]): TaxRate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NatId;
    purchasePrice: bigint;
    name: string;
    unit: bigint;
    sellingPrice: bigint;
    description: string;
    cessPercent: bigint;
    isActive: boolean;
    itemType: _ItemType;
    gstRate: bigint;
    hsnSacCode: string;
    openingStock: bigint;
}): {
    id: NatId;
    purchasePrice: bigint;
    name: string;
    unit: bigint;
    sellingPrice: bigint;
    description: string;
    cessPercent: bigint;
    isActive: boolean;
    itemType: ItemType;
    gstRate: bigint;
    hsnSacCode: string;
    openingStock: bigint;
} {
    return {
        id: value.id,
        purchasePrice: value.purchasePrice,
        name: value.name,
        unit: value.unit,
        sellingPrice: value.sellingPrice,
        description: value.description,
        cessPercent: value.cessPercent,
        isActive: value.isActive,
        itemType: from_candid_ItemType_n14(_uploadFile, _downloadFile, value.itemType),
        gstRate: value.gstRate,
        hsnSacCode: value.hsnSacCode,
        openingStock: value.openingStock
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NatId;
    pan: string;
    stateCode: bigint;
    billingAddress: string;
    name: string;
    isActive: boolean;
    email: string;
    gstin: string;
    shippingAddress: string;
    partyType: _PartyType;
    phone: string;
}): {
    id: NatId;
    pan: string;
    stateCode: bigint;
    billingAddress: string;
    name: string;
    isActive: boolean;
    email: string;
    gstin: string;
    shippingAddress: string;
    partyType: PartyType;
    phone: string;
} {
    return {
        id: value.id,
        pan: value.pan,
        stateCode: value.stateCode,
        billingAddress: value.billingAddress,
        name: value.name,
        isActive: value.isActive,
        email: value.email,
        gstin: value.gstin,
        shippingAddress: value.shippingAddress,
        partyType: from_candid_PartyType_n19(_uploadFile, _downloadFile, value.partyType),
        phone: value.phone
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stateCode: bigint;
    businessName: string;
    gstin: string;
    address: string;
    registrationType: _RegistrationType;
    contactDetails: string;
}): {
    stateCode: bigint;
    businessName: string;
    gstin: string;
    address: string;
    registrationType: RegistrationType;
    contactDetails: string;
} {
    return {
        stateCode: value.stateCode,
        businessName: value.businessName,
        gstin: value.gstin,
        address: value.address,
        registrationType: from_candid_RegistrationType_n24(_uploadFile, _downloadFile, value.registrationType),
        contactDetails: value.contactDetails
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: null;
} | {
    goods: null;
}): ItemType {
    return "service" in value ? ItemType.service : "goods" in value ? ItemType.goods : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    both: null;
} | {
    vendor: null;
}): PartyType {
    return "customer" in value ? PartyType.customer : "both" in value ? PartyType.both : "vendor" in value ? PartyType.vendor : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unregistered: null;
} | {
    regular: null;
} | {
    composition: null;
}): RegistrationType {
    return "unregistered" in value ? RegistrationType.unregistered : "regular" in value ? RegistrationType.regular : "composition" in value ? RegistrationType.composition : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Item>): Array<Item> {
    return value.map((x)=>from_candid_Item_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Party>): Array<Party> {
    return value.map((x)=>from_candid_Party_n17(_uploadFile, _downloadFile, x));
}
function to_candid_BusinessProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessProfile): _BusinessProfile {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_ItemType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): _ItemType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Item_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Item): _Item {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PartyType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartyType): _PartyType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Party_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Party): _Party {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_RegistrationType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationType): _RegistrationType {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: NatId;
    purchasePrice: bigint;
    name: string;
    unit: bigint;
    sellingPrice: bigint;
    description: string;
    cessPercent: bigint;
    isActive: boolean;
    itemType: ItemType;
    gstRate: bigint;
    hsnSacCode: string;
    openingStock: bigint;
}): {
    id: _NatId;
    purchasePrice: bigint;
    name: string;
    unit: bigint;
    sellingPrice: bigint;
    description: string;
    cessPercent: bigint;
    isActive: boolean;
    itemType: _ItemType;
    gstRate: bigint;
    hsnSacCode: string;
    openingStock: bigint;
} {
    return {
        id: value.id,
        purchasePrice: value.purchasePrice,
        name: value.name,
        unit: value.unit,
        sellingPrice: value.sellingPrice,
        description: value.description,
        cessPercent: value.cessPercent,
        isActive: value.isActive,
        itemType: to_candid_ItemType_n3(_uploadFile, _downloadFile, value.itemType),
        gstRate: value.gstRate,
        hsnSacCode: value.hsnSacCode,
        openingStock: value.openingStock
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stateCode: bigint;
    businessName: string;
    gstin: string;
    address: string;
    registrationType: RegistrationType;
    contactDetails: string;
}): {
    stateCode: bigint;
    businessName: string;
    gstin: string;
    address: string;
    registrationType: _RegistrationType;
    contactDetails: string;
} {
    return {
        stateCode: value.stateCode,
        businessName: value.businessName,
        gstin: value.gstin,
        address: value.address,
        registrationType: to_candid_RegistrationType_n34(_uploadFile, _downloadFile, value.registrationType),
        contactDetails: value.contactDetails
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: NatId;
    pan: string;
    stateCode: bigint;
    billingAddress: string;
    name: string;
    isActive: boolean;
    email: string;
    gstin: string;
    shippingAddress: string;
    partyType: PartyType;
    phone: string;
}): {
    id: _NatId;
    pan: string;
    stateCode: bigint;
    billingAddress: string;
    name: string;
    isActive: boolean;
    email: string;
    gstin: string;
    shippingAddress: string;
    partyType: _PartyType;
    phone: string;
} {
    return {
        id: value.id,
        pan: value.pan,
        stateCode: value.stateCode,
        billingAddress: value.billingAddress,
        name: value.name,
        isActive: value.isActive,
        email: value.email,
        gstin: value.gstin,
        shippingAddress: value.shippingAddress,
        partyType: to_candid_PartyType_n7(_uploadFile, _downloadFile, value.partyType),
        phone: value.phone
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationType): {
    unregistered: null;
} | {
    regular: null;
} | {
    composition: null;
} {
    return value == RegistrationType.unregistered ? {
        unregistered: null
    } : value == RegistrationType.regular ? {
        regular: null
    } : value == RegistrationType.composition ? {
        composition: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): {
    service: null;
} | {
    goods: null;
} {
    return value == ItemType.service ? {
        service: null
    } : value == ItemType.goods ? {
        goods: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartyType): {
    customer: null;
} | {
    both: null;
} | {
    vendor: null;
} {
    return value == PartyType.customer ? {
        customer: null
    } : value == PartyType.both ? {
        both: null
    } : value == PartyType.vendor ? {
        vendor: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
